# Generated by Django 4.0 on 2022-01-01 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='socialmedia',
            field=models.URLField(default='', max_length=255),
        ),
    ]
